// src/components/atoms/Socials.tsx
import React from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faFacebookF,
  faGithub,
  faInstagram,
  faLinkedin,
  faStackOverflow,
  faTwitter,
} from '@fortawesome/free-brands-svg-icons';

const Socials: React.FC = () => {
  const socials = [
    {
      label: 'Facebook',
      icon: <FontAwesomeIcon icon={faFacebookF} />,
      url: 'https://www.facebook.com/',
    },
    {
      label: 'Twitter',
      icon: <FontAwesomeIcon icon={faTwitter} />,
      url: 'https://twitter.com/stormix_co',
    },
    {
      label: 'Github',
      icon: <FontAwesomeIcon icon={faGithub} />,
      url: 'https://github.com/Stormix',
    },
    {
      label: 'Linkedin',
      icon: <FontAwesomeIcon icon={faLinkedin} />,
      url: 'https://www.linkedin.com/in/anasmazouni/',
    },
    {
      label: 'Instagram',
      icon: <FontAwesomeIcon icon={faInstagram} />,
      url: 'https://www.instagram.com/stormix.co/',
    },
    {
      label: 'StackOverflow',
      icon: <FontAwesomeIcon icon={faStackOverflow} />,
      url: 'https://stackoverflow.com/users/3370660/stormix',
    },
  ];
  return (
    <div className="flex flex-col w-4 gap-4 text-white">
      {socials.map((social) => (
        <a
          key={social.url}
          href={social.url}
          target="_blank"
          className="transition-colors hover:text-primary"
          rel="noreferrer"
        >
          {social.icon}
        </a>
      ))}
      <div className="h-12 ml-[5px] border-l border-white" />
    </div>
  );
};

export default Socials;

// src/components/Socials.vue
<template>
  <div class="py-4 mb-10">
    <ul class="flex flex-row gap-6 text-lg">
      <li v-for="social in socials" :key="social.title">
        <a :href="social.link" target="_blank" :title="`Follow Stromix on ${social.title}`">
          <span :class="social.icon" />
        </a>
      </li>
    </ul>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export interface Social {
  title: string;
  icon: string;
  link: string;
}
export default defineComponent({
  setup() {
    const socials: Social[] = [
      {
        title: "Facebook",
        icon: "ti-facebook",
        link: "https://www.facebook.com/stormiix",
      },
      {
        title: "Twitter",
        icon: "ti-twitter",
        link: "https://www.twitter.com/stormix_co",
      },
      {
        title: "Linkedin",
        icon: "ti-linkedin",
        link: "https://www.linkedin.com/in/anasmazouni/",
      },
      {
        title: "Instagram",
        icon: "ti-instagram",
        link: "https://instagram.com/stormix.co",
      },
      {
        title: "Github",
        icon: "ti-github",
        link: "https://github.com/stormix",
      },
      {
        title: "StackOverflow",
        icon: "ti-stack-overflow",
        link: "https://stackoverflow.com/users/3370660/stormix",
      },
      {
        title: "Medium",
        icon: "fab fa-medium-m",
        link: "https://medium.com/@anasmazouni",
      },
    ];

    return {
      socials,
    };
  },
});
</script>
